### ISSUE TITLE
Display issues, garbled output

### ISSUE THREAD

**Issue by duncanSplunkan** [jesuschrist-official/jcfb#1]
Everything compiles fine but when I try to run the samples, the image output is garbled. With the ttf sample there's red lines and a mess of blue pixels at the stop of the screen. I tried to run the print sample with the player.bmp image as input and I can see and recognize the image by the blue and purple but it's slanted to the right. I suspect this is due to framebuffer resolution issues. My display is 768 * 1366, that could have something to do with it. 

My apologies if this isn't well-written or I need to provide more information. This is my first Github issue.

**Comment by jesuschrist-official** [comment]
Hey,
I suspect that on certain devices, the framebuffer has not the memory layout I expect it to has, in perticular, that the line length of the framebuffer in memory could be different than the x resolution returned in the `fb_var_screeninfo`.

To help me to diagnose that, can you modify the `jcfb_start()` function by adding following code at line 106 (https://github.com/jesuschrist-official/jcfb/blob/master/src/jcfb.c#L106):
```
printf("xres: %u, yres: %u, bpp: %u, line_length: %u\n", var_si.xres, var_si.yres, var_si.bits_per_pixel, fix_si.line_length);
printf("virtual xres: %u, virtual yres: %u\n", var_si.xres_virtual, var_si.yres_virtual);
printf("type: %u, type_aux: %u, visual: %u\n", fix_si.type, fix_si.type_aux, fix_si.visual);
return -1;
```

If `var_si.xres * (var_si.bits_per_pixel / 8) != fix_si.line_length`, this should be the answer

Otherwise I will add a way to do logs that you could send me.

https://www.kernel.org/doc/Documentation/fb/api.txt

EDIT: I would be a bit surprised this could be the issue, since the line length in fix_si is not dependant of the current screen resolution.

However, according to above doc : 
```
Padding at end of lines may be present and is then reported through the fixed
screen information line_length field.
```

**Comment by duncanSplunkan** [comment]
I modified the function as you said and the output is as follows:
```
xres: 1366, yres: 768, bpp: 32, line_length: 5504
virtual xres: 1366, virtual yres: 768
type: 0, type_aux: 0, visual: 2
Cannot start JCFB
```

That means that 1366 * (32 / 8) = 5464 and not 5504.

**Comment by jesuschrist-official** [comment]
Thank you !
So we may need to add some padding in `_draw_frame()` : https://github.com/jesuschrist-official/jcfb/blob/master/src/jcfb.c#L55
Replace the function with this code : 
```
static void _draw_frame(bitmap_t* bmp) {
    uint8_t* dest = _FB.mem;
    size_t bpp = _FB.var_si.bits_per_pixel / 8;
    pixel_t* src = bmp->mem;
    for (size_t i  = 0; i < bmp->w * bmp->h; i++) {
        memcpy(dest, src, bpp);
        dest += bpp;
        src++;
        // Pad destination when reaching end of a row
        if (i % bmp->w == bmp->w - 1) {
            dest += (5504 - 5464) / 8;
        }
    }
}
```

Hoping this will be the answer

**Comment by duncanSplunkan** [comment]
Hm, it leads to a segmentation fault but it does seem to print something different before it happens, it's the image but slanted slightly more. Out of curiosity I switched 5504 and 5464 in the code you gave me and it didn't lead to a segmentation fault and seems to print the same result but shifted to the right.

**Comment by jesuschrist-official** [comment]
Well, the line length is measured in bytes (and not in bits), so a line in your case is 40 bytes longer than a "pixel" line.

Try to replace `dest += (5504 - 5464) / 8` by `dest += 40` and stop the loop at half its process (to avoid segfault, and see if the display is consistant).

The fact the image is slanted left or right may just be dependant of the congruence of the padding with the line length. The fact that you use a negative value for the padding make no sense.

I don't think this will work (the +40) because of the segfault :p

**Comment by duncanSplunkan** [comment]
It prints the image successfully! Although it has a segmentation fault afterwards. The mandelbrot program also seems to print an output before segfaulting.

**Comment by jesuschrist-official** [comment]
The image is printed correctly ? Nice!

Maybe the segfault is not issued by the `_draw_frame()` function. You can build the project in debug mode (`make clean && make DEBUG=1`), and run the program in gdb.

Before you start that, be sure to know how to use your rescue key (on many system it is the "Print" key I guess) : https://en.wikipedia.org/wiki/Magic_SysRq_key

Try ALT + SYSRQ + H in a TTY to see if it properly show you the SYSRQ help message.

When the program segfault and if pressing a key  on the keyboard give strange input in GDB, use the SYSRQ + ALT + R keys to reset the keyboard layout from the raw mode.

**Comment by duncanSplunkan** [comment]
Hm, I did some debugging and as it seems the segfault is issued by `_draw_frame_()` and it's probably related to the looping. I think it may have something to do with the adding to `dest` and the `memcpy` call but I'm not sure.

**Comment by jesuschrist-official** [comment]
Oh, I get it ! I think that when I do the `mmap()` call (https://github.com/jesuschrist-official/jcfb/blob/master/src/jcfb.c#L141) I use the `_FB_memsize()` function that doesn't take into account the fact that a "pixel" line has not the size of a "hardware" line, so the mapping size is too small.

Although I'm almost sure of that, check with this `_FB_memsize()` function :
```
static size_t _FB_memsize() {
    return ( _FB.fix_si.line_length
            * _FB.var_si.yres_virtual
            * _FB.var_si.bits_per_pixel) / 8;
}
```

I'll publish a fix for all this bunch tonight (or soon). Can you give me the context you're running JCFB on ? (Hardware, OS) Maybe I could reproduce the issue at home !

Thank you for your time, I'm really pleased of your help in fixing this issue 👍 

(I'll also add more check in the JCFB initialisation process to catch non-supported configuration, I guess it will be a good idea to prevent errors I cannot deal with (bizarre pixel layouts, etc))

EDIT: I think we should use `_FB.fix_si.smem_len` as FB memory size

**Comment by duncanSplunkan** [comment]
Hm, it seems like neither solution works. I'm running it on a HP Stream 11 with 2 GB of RAM and an Intel Celeron at 2.4 GHz. Here's an Amazon link with more detailed specs: `https://www.amazon.co.uk/dp/B01N9JKIAU/ref=twister_B073VRZCB3?_encoding=UTF8&psc=1`
My OS is Debian 9.8.

I'm glad I'm able to help out!

**Comment by jesuschrist-official** [comment]
I'm surprised, can you give me the value of _FB.fix_si.smem_len ? And mmio_mem ?

I will try on my old laptop with your resolution to see if I can reproduce, it would be simpler to fix this bug than with this ping-pong chat !

Anyway, it appears that the size of the memory mapped area is not right. To confirm that, please modify the _draw_frame() to not display the last line (i < w * h - w in the for loop).

**Comment by duncanSplunkan** [comment]
`_FB.fix_si.smem_len` is 4227072. I wasn't able to find `mmio_mem`, though. Removing the last line just causes a segmentation fault, so I think the mapped area isn't right that means. Good luck fixing it!

**Comment by jesuschrist-official** [comment]
Hey, I've published a first fix attempt there : https://github.com/jesuschrist-official/jcfb/tree/fix-issue-1
Can you try it and say me if it's better or not ?

**Comment by duncanSplunkan** [comment]
It works flawlessly now, thank you! The image displays correctly on both my 768 * 1366 display and a virtual machine with a 600 * 800 display and there's no segmentation faults.

**Comment by jesuschrist-official** [comment]
Very nice, hoping you'll be able to do nice things with JCFB ;-)
If you have questions or remarks, feel free to ask them !

**Comment by jesuschrist-official** [comment]
Very nice, hoping you'll be able to do nice things with JCFB ;-)
If you have questions or remarks, feel free to ask them !

**Comment by duncanSplunkan** [comment]
Thank you! Have a nice day!
